package controleatleta.ui;

import controleatleta.Partida;
import controleatleta.util.FabricaMaskFormatter;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.MaskFormatter;

public class CadastroPartida extends javax.swing.JDialog {

    private Partida partida;
    private SimpleDateFormat dateFormat;

    public Partida getPartida() {
        return partida;
    }

    /**
     * Creates new form CadastroPartida
     */
    public CadastroPartida(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        initComponents();
    }

    private void salvarPartida() {        
        char tipo;
        Date data = null;
        
        if(tipoCampo.getSelectedIndex() == 0)
            tipo = 'A';
        else
            tipo = 'O';
        
        try {
            data = dateFormat.parse(dataCampo.getText());
        } catch (ParseException ex) {
            Logger.getLogger(CadastroPartida.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        partida = new Partida(data, tipo, jgPelaSelecaoCampo.isSelected());
        partida.setFaltasCometidas(Short.parseShort(jTextFieldFaltasCometidas.getText()));
        partida.setFaltasSofridas(Short.parseShort(jTextFieldFaltasSofridas.getText()));
        partida.setPontuacao(Short.parseShort(jTextFieldPontuacao.getText()));
        partida.setQtdLancesLivres(Short.parseShort(jTextFieldQtdLancesLivres.getText()));
        partida.setQtdLancesLivresConvertidos(Short.parseShort(jTextFieldQtdLancesConvertidos.getText()));
        partida.setFoiVencedor(VenceuCampo.isSelected());      
    }

    private boolean validar() {

        if (!(validarCampoInteiro(jTextFieldPontuacao, "Pontuação")
                && validarCampoInteiro(jTextFieldFaltasCometidas, "Faltas cometidas")
                && validarCampoInteiro(jTextFieldFaltasSofridas, "Faltas Sofridas")
                && validarCampoInteiro(jTextFieldQtdLancesLivres, "Qtd de Lances Livres")
                && validarCampoInteiro(jTextFieldQtdLancesConvertidos, "Qtd de Lances Livres Convertidos"))) {
            return false;
        }

        
        if (dataCampo.getText().replace(" ", "").length() > 3) {
            try {
                dateFormat.parse(dataCampo.getText());
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this, "O valor do campo 'Data' é inválido.");
                dataCampo.requestFocus();
                return false;
            }
        }

        return true;
    }

    private boolean validarCampoInteiro(JTextField jTextField, String nomeCampo) {

        try {
            Integer.parseInt(jTextField.getText());
        } catch (Exception e) {
            jTextField.requestFocus();
            JOptionPane.showMessageDialog(this, "Erro no campo '" + nomeCampo + "'.");
            return false;
        }

        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        MaskFormatter ftm = null;
        try{
            ftm = FabricaMaskFormatter.getData();
        } catch(Exception e){
            System.out.println("erro na mascara.");
        }
        dataCampo = new javax.swing.JFormattedTextField(ftm);
        jLabel3 = new javax.swing.JLabel();
        tipoCampo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPontuacao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldQtdLancesConvertidos = new javax.swing.JTextField();
        jTextFieldQtdLancesLivres = new javax.swing.JTextField();
        jTextFieldFaltasSofridas = new javax.swing.JTextField();
        jTextFieldFaltasCometidas = new javax.swing.JTextField();
        adicionar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        VenceuCampo = new javax.swing.JCheckBox();
        jgPelaSelecaoCampo = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Partida:");

        jLabel2.setText("Data:");

        jLabel3.setText("Tipo:");

        tipoCampo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Amistoso", "Oficial"}));

        jLabel4.setText("Pontuação:");

        jTextFieldPontuacao.setText("0");
        jTextFieldPontuacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPontuacaoActionPerformed(evt);
            }
        });

        jLabel5.setText("Faltas Cometidas:");

        jLabel6.setText("Faltas Sofridas:");

        jLabel7.setText("Qtd Lances Livres:");

        jLabel8.setText("Qtd Lances Livres Convertidos:");

        jTextFieldQtdLancesConvertidos.setText("0");
        jTextFieldQtdLancesConvertidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQtdLancesConvertidosActionPerformed(evt);
            }
        });

        jTextFieldQtdLancesLivres.setText("0");

        jTextFieldFaltasSofridas.setText("0");

        jTextFieldFaltasCometidas.setText("0");

        adicionar.setText("Adicionar");
        adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        VenceuCampo.setText("Venceu");
        VenceuCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VenceuCampoActionPerformed(evt);
            }
        });

        jgPelaSelecaoCampo.setText("Jogo Pela Seleção Nacional");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(VenceuCampo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jgPelaSelecaoCampo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tipoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dataCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPontuacao, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFaltasCometidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFaltasSofridas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldQtdLancesLivres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldQtdLancesConvertidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(adicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFieldFaltasCometidas, jTextFieldFaltasSofridas, jTextFieldPontuacao, jTextFieldQtdLancesConvertidos, jTextFieldQtdLancesLivres});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dataCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldPontuacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tipoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldFaltasCometidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldFaltasSofridas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldQtdLancesLivres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldQtdLancesConvertidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VenceuCampo)
                    .addComponent(jgPelaSelecaoCampo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(adicionar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VenceuCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VenceuCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VenceuCampoActionPerformed

    private void jTextFieldQtdLancesConvertidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQtdLancesConvertidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQtdLancesConvertidosActionPerformed

    private void jTextFieldPontuacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPontuacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPontuacaoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:     
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarActionPerformed
        // TODO add your handling code here:
        if(validar()){
            this.salvarPartida();
            this.setVisible(false);
        }
    }//GEN-LAST:event_adicionarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox VenceuCampo;
    private javax.swing.JButton adicionar;
    private javax.swing.JFormattedTextField dataCampo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldFaltasCometidas;
    private javax.swing.JTextField jTextFieldFaltasSofridas;
    private javax.swing.JTextField jTextFieldPontuacao;
    private javax.swing.JTextField jTextFieldQtdLancesConvertidos;
    private javax.swing.JTextField jTextFieldQtdLancesLivres;
    private javax.swing.JCheckBox jgPelaSelecaoCampo;
    private javax.swing.JComboBox tipoCampo;
    // End of variables declaration//GEN-END:variables
}
